import { getCustomRepository } from 'typeorm'
import ScheduleRepository from '../database/repository/ScheduleRepository'
import connection from '../database/connection'

const run = async () => {
  await connection()
  const scheduleRepository = getCustomRepository(ScheduleRepository)

  await scheduleRepository.insert([
    {
      neighborhood: 'Ariston Gomes',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Bela Vista',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Centro',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Conjunto Águas Claras',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Conjunto Habitac Andorinhas',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Goiás',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Goiás II',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Jardim Arco Íris',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Jardim Arco-íris',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Jardim Monte Alto',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Jardim Novo Horizont III',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Jardim Novo Horizonte',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Jardim Novo Horizonte I',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Jardim Novo Horizonte II',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Jardim Oliveiras',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Jardim Urânio',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Joaquim Berto',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Loteamento Perne',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Loteamento São Paulo Cruz',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Mato Grosso',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Mato Grosso do Sul',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Novo Horizonte',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Novo Iporá',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Padre Cícero',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Parque das Estrelas',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Parque Estrelas',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Pedro G Filho',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Perne',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Planalto',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Por do Sol',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Setor Central',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Setor José',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Setor Por do Sol',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Santo Antônio',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'São Francisco',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'São José',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'São Paulo da Cruz',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Setor Aeroporto Sul',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Setor Ariston Gomes',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Setor Bela Vista',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Setor Carajás',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Setor Central',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Setor dos Funcionário',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Setor dos Funcionários Ii',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Setor Estrela Norte',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Setor Funcionários',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Setor Leste',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Setor Perme',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Setor Por do Sol',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Setor Por Sol',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Setor Rosa Ventos',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Sítio Perme',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Sossego',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Umuarama',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Vila Brasília',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Vila Brasília 1',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Vila Cascalheira',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Vila Ferreira',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Vila Iporazinho',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Vila Itajubá',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Vila Itajubá I',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Vila Itajubá II',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Vila Monte Alto',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Vila Moreira',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Vila Mutirão',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Vila Nova',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Vila Padre Cícero',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Vila Rica',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Vila Umuarama',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Vila União',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      neighborhood: 'Zona Rural',
      start: '',
      end: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
  ])

  process.exit(0)
}

run()
